import airsim
import numpy
import Swarmer
import time
import CollisionDetection
import WaypointList
import SwarmPathing
import Vector3D 

client1 = airsim.MultirotorClient()
client2 = airsim.MultirotorClient()
client1.confirmConnection()
client2.confirmConnection()
d = len(client1.simListSceneObjects(name_regex= 'Drone.*')) + len(client2.simListSceneObjects(name_regex= 'Drone.*'))

#client = airsim.MultirotorClient()
#client.confirmConnection()
Swarming = Swarmer.Swarmer()
cd = CollisionDetection.CollisionDetection()
wpl = WaypointList.WaypointList()
wpl1 = WaypointList.WaypointList()
SwarmPathing = SwarmPathing.SwarmPathing()
v3d = Vector3D.Vector3D()
#d = len(client.simListSceneObjects(name_regex = 'Drone.*'))
print("Number of drones: ", d)
wpl.addWayPoint([-200,0,-100],4)
wpl1.addWayPoint([200,0,-100],4)


if d == 0:
    #client1.enableApiControl(True, "Lead")
    #client1.armDisarm(True, "Lead")
    #client1.takeoffAsync(vehicle_name="Lead").join()
    #client1.moveToZAsync(-50, 10,vehicle_name="Lead").join()

    client.enableApiControl(True, "Lead")
    client.armDisarm(True, "Lead")
    client.takeoffAsync(vehicle_name="Lead").join()
    client.moveToZAsync(-50, 10,vehicle_name="Lead").join()
    while True:
        #cd.collisionDetection("Lead",wpl,client1)
        #SwarmPathing.pathCheck(wpl,"Lead",client1)
        #SwarmPathing.pathTo(wpl,"Lead",client1)

        cd.collisionDetection("Lead",wpl,client)
        SwarmPathing.pathCheck(wpl,"Lead",client)
        SwarmPathing.pathTo(wpl,"Lead",client)
        time.sleep(0.1)

    

if d == 2:
    client1.enableApiControl(True, "Lead")
    client1.armDisarm(True, "Lead")
    client2.enableApiControl(True, "Drone1")
    client2.armDisarm(True, "Drone1")

    client1.takeoffAsync(vehicle_name="Lead")
    client2.takeoffAsync(vehicle_name="Drone1")

    client1.moveToZAsync(-100, 10,vehicle_name="Lead")
    client2.moveToZAsync(-100, 10,vehicle_name="Drone1").join()

    #client.enableApiControl(True, "Lead")
    #client.armDisarm(True, "Lead")
    #client.enableApiControl(True, "Drone1")
    #client.armDisarm(True, "Drone1")

    #client.takeoffAsync(vehicle_name="Lead")
    #client.takeoffAsync(vehicle_name="Drone1").join()

    #client.moveToZAsync(-100, 10,vehicle_name="Lead")
    #client.moveToZAsync(-100, 10,vehicle_name="Drone1").join()
    while True:
        cd.collisionDetection("Lead",wpl,client1)
        cd.collisionDetection("Drone1",wpl1,client2)
        time.sleep(1)
        SwarmPathing.pathCheck(wpl,"Lead",client1)
        SwarmPathing.pathCheck(wpl1,"Drone1",client2)
        SwarmPathing.pathTo(wpl,"Lead",client1,v3d)
        SwarmPathing.pathTo(wpl1,"Drone1",client2,v3d)

        #cd.collisionDetection("Lead",wpl,client)
        #cd.collisionDetection("Drone1",wpl1,client)
        #SwarmPathing.pathCheck(wpl,"Lead",client)
        #SwarmPathing.pathCheck(wpl1,"Drone1",client)
        #SwarmPathing.pathTo(wpl,"Lead",client,v3d)
        #SwarmPathing.pathTo(wpl1,"Drone1",client,v3d)
        
        


    f1 = client.moveToZAsync(-0.1, 5,vehicle_name="Lead")
    f2 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone1")
    f1.join()
    f2.join()
    f1 = client.landAsync(vehicle_name="Lead")
    f2 = client.landAsync(vehicle_name="Drone1")
    f1.join()
    f2.join()
    client.armDisarm(False, "Lead")
    client.armDisarm(False, "Drone1")
    client.enableApiControl(False, "Lead")
    client.enableApiControl(False, "Drone1")
    
if d == 20:
    client.enableApiControl(True, "Lead")
    client.enableApiControl(True, "Drone1")
    client.enableApiControl(True, "Drone2")
    client.armDisarm(True, "Lead")
    client.armDisarm(True, "Drone1")
    client.armDisarm(True, "Drone2")


    Swarming.formSwarm(d)
    
   
    f1 = client.moveToZAsync(-0.1, 5,vehicle_name="Lead")
    f2 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone1")
    f3 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone2")
    f3.join()
    f2.join()
    f1.join()

    f1 = client.landAsync(vehicle_name="Lead")
    f2 = client.landAsync(vehicle_name="Drone1")
    f3 = client.landAsync(vehicle_name="Drone2")
    f3.join()
    f2.join()
    f1.join()

    client.armDisarm(False, "Lead")
    client.armDisarm(False, "Drone1")
    client.armDisarm(False, "Drone2")
    client.enableApiControl(False, "Lead")
    client.enableApiControl(False, "Drone1")
    client.enableApiControl(False, "Drone2")

if d == 3:
    client.enableApiControl(True, "Lead")
    client.enableApiControl(True, "Drone1")
    client.enableApiControl(True, "Drone2")
    client.enableApiControl(True, "Drone3")
    client.armDisarm(True, "Lead")
    client.armDisarm(True, "Drone1")
    client.armDisarm(True, "Drone2")
    client.armDisarm(True, "Drone3")


    Swarming.formSwarm(d)


    f1 = client.moveToZAsync(-0.1, 5,vehicle_name="Lead")
    f2 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone1")
    f3 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone2")
    f4 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone3")
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    f1 = client.landAsync(vehicle_name="Lead")
    f2 = client.landAsync(vehicle_name="Drone1")
    f3 = client.landAsync(vehicle_name="Drone2")
    f4 = client.landAsync(vehicle_name="Drone3")
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    client.armDisarm(False, "Lead")
    client.armDisarm(False, "Drone1")
    client.armDisarm(False, "Drone2")
    client.armDisarm(False, "Drone3")
    client.enableApiControl(False, "Lead")
    client.enableApiControl(False, "Drone1")
    client.enableApiControl(False, "Drone2")
    client.enableApiControl(False, "Drone3")
if d == 4:
    client.enableApiControl(True, "Lead")
    client.enableApiControl(True, "Drone1")
    client.enableApiControl(True, "Drone2")
    client.enableApiControl(True, "Drone3")
    client.enableApiControl(True, "Drone4")
    client.armDisarm(True, "Lead")
    client.armDisarm(True, "Drone1")
    client.armDisarm(True, "Drone2")
    client.armDisarm(True, "Drone3")
    client.armDisarm(True, "Drone4")


    Swarming.formSwarm(d)


    f1 = client.moveToZAsync(-0.1, 5,vehicle_name="Lead")
    f2 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone1")
    f3 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone2")
    f4 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone3")
    f5 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone4")
    f5.join()
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    f1 = client.landAsync(vehicle_name="Lead")
    f2 = client.landAsync(vehicle_name="Drone1")
    f3 = client.landAsync(vehicle_name="Drone2")
    f4 = client.landAsync(vehicle_name="Drone3")
    f5 = client.landAsync(vehicle_name="Drone4")
    f5.join()
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    client.armDisarm(False, "Lead")
    client.armDisarm(False, "Drone1")
    client.armDisarm(False, "Drone2")
    client.armDisarm(False, "Drone3")
    client.armDisarm(False, "Drone4")
    client.enableApiControl(False, "Lead")
    client.enableApiControl(False, "Drone1")
    client.enableApiControl(False, "Drone2")
    client.enableApiControl(False, "Drone3")
    client.enableApiControl(False, "Drone4")
if d == 5:
    client.enableApiControl(True, "Lead")
    client.enableApiControl(True, "Drone1")
    client.enableApiControl(True, "Drone2")
    client.enableApiControl(True, "Drone3")
    client.enableApiControl(True, "Drone4")
    client.enableApiControl(True, "Drone5")
    client.armDisarm(True, "Lead")
    client.armDisarm(True, "Drone1")
    client.armDisarm(True, "Drone2")
    client.armDisarm(True, "Drone3")
    client.armDisarm(True, "Drone4")
    client.armDisarm(True, "Drone5")


    Swarming.formSwarm(d)


    f1 = client.moveToZAsync(-0.1, 5,vehicle_name="Lead")
    f2 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone1")
    f3 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone2")
    f4 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone3")
    f5 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone4")
    f6 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone5")
    f6.join()
    f5.join()
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    f1 = client.landAsync(vehicle_name="Lead")
    f2 = client.landAsync(vehicle_name="Drone1")
    f3 = client.landAsync(vehicle_name="Drone2")
    f4 = client.landAsync(vehicle_name="Drone3")
    f5 = client.landAsync(vehicle_name="Drone4")
    f6 = client.landAsync(vehicle_name="Drone5")
    f6.join()
    f5.join()
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    client.armDisarm(False, "Lead")
    client.armDisarm(False, "Drone1")
    client.armDisarm(False, "Drone2")
    client.armDisarm(False, "Drone3")
    client.armDisarm(False, "Drone4")
    client.armDisarm(False, "Drone5")
    client.enableApiControl(False, "Lead")
    client.enableApiControl(False, "Drone1")
    client.enableApiControl(False, "Drone2")
    client.enableApiControl(False, "Drone3")
    client.enableApiControl(False, "Drone4")
    client.enableApiControl(False, "Drone5")
if d == 6:
    client.enableApiControl(True, "Lead")
    client.enableApiControl(True, "Drone1")
    client.enableApiControl(True, "Drone2")
    client.enableApiControl(True, "Drone3")
    client.enableApiControl(True, "Drone4")
    client.enableApiControl(True, "Drone5")
    client.enableApiControl(True, "Drone6")
    client.armDisarm(True, "Lead")
    client.armDisarm(True, "Drone1")
    client.armDisarm(True, "Drone2")
    client.armDisarm(True, "Drone3")
    client.armDisarm(True, "Drone4")
    client.armDisarm(True, "Drone5")
    client.armDisarm(True, "Drone6")


    Swarming.formSwarm(d)


    f1 = client.moveToZAsync(-0.1, 5,vehicle_name="Lead")
    f2 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone1")
    f3 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone2")
    f4 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone3")
    f5 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone4")
    f6 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone5")
    f7 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone6")
    f7.join()
    f6.join()
    f5.join()
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    f1 = client.landAsync(vehicle_name="Lead")
    f2 = client.landAsync(vehicle_name="Drone1")
    f3 = client.landAsync(vehicle_name="Drone2")
    f4 = client.landAsync(vehicle_name="Drone3")
    f5 = client.landAsync(vehicle_name="Drone4")
    f6 = client.landAsync(vehicle_name="Drone5")
    f7 = client.landAsync(vehicle_name="Drone6")
    f7.join()
    f6.join()
    f5.join()
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    client.armDisarm(False, "Lead")
    client.armDisarm(False, "Drone1")
    client.armDisarm(False, "Drone2")
    client.armDisarm(False, "Drone3")
    client.armDisarm(False, "Drone4")
    client.armDisarm(False, "Drone5")
    client.armDisarm(False, "Drone6")
    client.enableApiControl(False, "Lead")
    client.enableApiControl(False, "Drone1")
    client.enableApiControl(False, "Drone2")
    client.enableApiControl(False, "Drone3")
    client.enableApiControl(False, "Drone4")
    client.enableApiControl(False, "Drone5")
    client.enableApiControl(False, "Drone6")
if d == 7:
    client.enableApiControl(True, "Lead")
    client.enableApiControl(True, "Drone1")
    client.enableApiControl(True, "Drone2")
    client.enableApiControl(True, "Drone3")
    client.enableApiControl(True, "Drone4")
    client.enableApiControl(True, "Drone5")
    client.enableApiControl(True, "Drone6")
    client.enableApiControl(True, "Drone7")
    client.armDisarm(True, "Lead")
    client.armDisarm(True, "Drone1")
    client.armDisarm(True, "Drone2")
    client.armDisarm(True, "Drone3")
    client.armDisarm(True, "Drone4")
    client.armDisarm(True, "Drone5")
    client.armDisarm(True, "Drone6")
    client.armDisarm(True, "Drone7")


    Swarming.formSwarm(d)


    f1 = client.moveToZAsync(-0.1, 5,vehicle_name="Lead")
    f2 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone1")
    f3 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone2")
    f4 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone3")
    f5 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone4")
    f6 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone5")
    f7 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone6")
    f8 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone7")
    f8.join()
    f7.join()
    f6.join()
    f5.join()
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    f1 = client.landAsync(vehicle_name="Lead")
    f2 = client.landAsync(vehicle_name="Drone1")
    f3 = client.landAsync(vehicle_name="Drone2")
    f4 = client.landAsync(vehicle_name="Drone3")
    f5 = client.landAsync(vehicle_name="Drone4")
    f6 = client.landAsync(vehicle_name="Drone5")
    f7 = client.landAsync(vehicle_name="Drone6")
    f8 = client.landAsync(vehicle_name="Drone7")
    f8.join()
    f7.join()
    f6.join()
    f5.join()
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    client.armDisarm(False, "Lead")
    client.armDisarm(False, "Drone1")
    client.armDisarm(False, "Drone2")
    client.armDisarm(False, "Drone3")
    client.armDisarm(False, "Drone4")
    client.armDisarm(False, "Drone5")
    client.armDisarm(False, "Drone6")
    client.armDisarm(False, "Drone7")
    client.enableApiControl(False, "Lead")
    client.enableApiControl(False, "Drone1")
    client.enableApiControl(False, "Drone2")
    client.enableApiControl(False, "Drone3")
    client.enableApiControl(False, "Drone4")
    client.enableApiControl(False, "Drone5")
    client.enableApiControl(False, "Drone6")
    client.enableApiControl(False, "Drone7")
if d == 8:
    client.enableApiControl(True, "Lead")
    client.enableApiControl(True, "Drone1")
    client.enableApiControl(True, "Drone2")
    client.enableApiControl(True, "Drone3")
    client.enableApiControl(True, "Drone4")
    client.enableApiControl(True, "Drone5")
    client.enableApiControl(True, "Drone6")
    client.enableApiControl(True, "Drone7")
    client.enableApiControl(True, "Drone8")
    client.armDisarm(True, "Lead")
    client.armDisarm(True, "Drone1")
    client.armDisarm(True, "Drone2")
    client.armDisarm(True, "Drone3")
    client.armDisarm(True, "Drone4")
    client.armDisarm(True, "Drone5")
    client.armDisarm(True, "Drone6")
    client.armDisarm(True, "Drone7")
    client.armDisarm(True, "Drone8")


    Swarming.formSwarm(d)


    f1 = client.moveToZAsync(-0.1, 5,vehicle_name="Lead")
    f2 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone1")
    f3 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone2")
    f4 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone3")
    f5 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone4")
    f6 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone5")
    f7 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone6")
    f8 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone7")
    f9 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone8")
    f9.join()
    f8.join()
    f7.join()
    f6.join()
    f5.join()
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    f1 = client.landAsync(vehicle_name="Lead")
    f2 = client.landAsync(vehicle_name="Drone1")
    f3 = client.landAsync(vehicle_name="Drone2")
    f4 = client.landAsync(vehicle_name="Drone3")
    f5 = client.landAsync(vehicle_name="Drone4")
    f6 = client.landAsync(vehicle_name="Drone5")
    f7 = client.landAsync(vehicle_name="Drone6")
    f8 = client.landAsync(vehicle_name="Drone7")
    f9 = client.landAsync(vehicle_name="Drone8")
    f9.join()
    f8.join()
    f7.join()
    f6.join()
    f5.join()
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    client.armDisarm(False, "Lead")
    client.armDisarm(False, "Drone1")
    client.armDisarm(False, "Drone2")
    client.armDisarm(False, "Drone3")
    client.armDisarm(False, "Drone4")
    client.armDisarm(False, "Drone5")
    client.armDisarm(False, "Drone6")
    client.armDisarm(False, "Drone7")
    client.armDisarm(False, "Drone8")
    client.enableApiControl(False, "Lead")
    client.enableApiControl(False, "Drone1")
    client.enableApiControl(False, "Drone2")
    client.enableApiControl(False, "Drone3")
    client.enableApiControl(False, "Drone4")
    client.enableApiControl(False, "Drone5")
    client.enableApiControl(False, "Drone6")
    client.enableApiControl(False, "Drone7")
    client.enableApiControl(False, "Drone8")