import airsim
import Swarming
client = airsim.MultirotorClient()
client.confirmConnection()

d = len(client.simListSceneObjects(name_regex = 'Drone.*'))
print("Number of drones: ", d)
if d == 2:
    client.enableApiControl(True, "Lead")
    client.enableApiControl(True, "Drone1")
    client.enableApiControl(True, "Drone2")
    client.armDisarm(True, "Lead")
    client.armDisarm(True, "Drone1")
    client.armDisarm(True, "Drone2")


    Swarming.formSwarm(d)
   
   
    f1 = client.moveToZAsync(-0.1, 5,vehicle_name="Lead")
    f2 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone1")
    f3 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone2")
    f3.join()
    f2.join()
    f1.join()

    f1 = client.landAsync(vehicle_name="Lead")
    f2 = client.landAsync(vehicle_name="Drone1")
    f3 = client.landAsync(vehicle_name="Drone2")
    f3.join()
    f2.join()
    f1.join()

    client.armDisarm(False, "Lead")
    client.armDisarm(False, "Drone1")
    client.armDisarm(False, "Drone2")
    client.enableApiControl(False, "Lead")
    client.enableApiControl(False, "Drone1")
    client.enableApiControl(False, "Drone2")

if d == 3:
    client.enableApiControl(True, "Lead")
    client.enableApiControl(True, "Drone1")
    client.enableApiControl(True, "Drone2")
    client.enableApiControl(True, "Drone3")
    client.armDisarm(True, "Lead")
    client.armDisarm(True, "Drone1")
    client.armDisarm(True, "Drone2")
    client.armDisarm(True, "Drone3")


    Swarming.formSwarm(d)


    f1 = client.moveToZAsync(-0.1, 5,vehicle_name="Lead")
    f2 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone1")
    f3 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone2")
    f4 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone3")
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    f1 = client.landAsync(vehicle_name="Lead")
    f2 = client.landAsync(vehicle_name="Drone1")
    f3 = client.landAsync(vehicle_name="Drone2")
    f4 = client.landAsync(vehicle_name="Drone3")
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    client.armDisarm(False, "Lead")
    client.armDisarm(False, "Drone1")
    client.armDisarm(False, "Drone2")
    client.armDisarm(False, "Drone3")
    client.enableApiControl(False, "Lead")
    client.enableApiControl(False, "Drone1")
    client.enableApiControl(False, "Drone2")
    client.enableApiControl(False, "Drone3")
if d == 4:
    client.enableApiControl(True, "Lead")
    client.enableApiControl(True, "Drone1")
    client.enableApiControl(True, "Drone2")
    client.enableApiControl(True, "Drone3")
    client.enableApiControl(True, "Drone4")
    client.armDisarm(True, "Lead")
    client.armDisarm(True, "Drone1")
    client.armDisarm(True, "Drone2")
    client.armDisarm(True, "Drone3")
    client.armDisarm(True, "Drone4")


    Swarming.formSwarm(d)


    f1 = client.moveToZAsync(-0.1, 5,vehicle_name="Lead")
    f2 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone1")
    f3 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone2")
    f4 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone3")
    f5 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone4")
    f5.join()
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    f1 = client.landAsync(vehicle_name="Lead")
    f2 = client.landAsync(vehicle_name="Drone1")
    f3 = client.landAsync(vehicle_name="Drone2")
    f4 = client.landAsync(vehicle_name="Drone3")
    f5 = client.landAsync(vehicle_name="Drone4")
    f5.join()
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    client.armDisarm(False, "Lead")
    client.armDisarm(False, "Drone1")
    client.armDisarm(False, "Drone2")
    client.armDisarm(False, "Drone3")
    client.armDisarm(False, "Drone4")
    client.enableApiControl(False, "Lead")
    client.enableApiControl(False, "Drone1")
    client.enableApiControl(False, "Drone2")
    client.enableApiControl(False, "Drone3")
    client.enableApiControl(False, "Drone4")
if d == 5:
    client.enableApiControl(True, "Lead")
    client.enableApiControl(True, "Drone1")
    client.enableApiControl(True, "Drone2")
    client.enableApiControl(True, "Drone3")
    client.enableApiControl(True, "Drone4")
    client.enableApiControl(True, "Drone5")
    client.armDisarm(True, "Lead")
    client.armDisarm(True, "Drone1")
    client.armDisarm(True, "Drone2")
    client.armDisarm(True, "Drone3")
    client.armDisarm(True, "Drone4")
    client.armDisarm(True, "Drone5")


    Swarming.formSwarm(d)


    f1 = client.moveToZAsync(-0.1, 5,vehicle_name="Lead")
    f2 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone1")
    f3 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone2")
    f4 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone3")
    f5 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone4")
    f6 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone5")
    f6.join()
    f5.join()
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    f1 = client.landAsync(vehicle_name="Lead")
    f2 = client.landAsync(vehicle_name="Drone1")
    f3 = client.landAsync(vehicle_name="Drone2")
    f4 = client.landAsync(vehicle_name="Drone3")
    f5 = client.landAsync(vehicle_name="Drone4")
    f6 = client.landAsync(vehicle_name="Drone5")
    f6.join()
    f5.join()
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    client.armDisarm(False, "Lead")
    client.armDisarm(False, "Drone1")
    client.armDisarm(False, "Drone2")
    client.armDisarm(False, "Drone3")
    client.armDisarm(False, "Drone4")
    client.armDisarm(False, "Drone5")
    client.enableApiControl(False, "Lead")
    client.enableApiControl(False, "Drone1")
    client.enableApiControl(False, "Drone2")
    client.enableApiControl(False, "Drone3")
    client.enableApiControl(False, "Drone4")
    client.enableApiControl(False, "Drone5")
if d == 6:
    client.enableApiControl(True, "Lead")
    client.enableApiControl(True, "Drone1")
    client.enableApiControl(True, "Drone2")
    client.enableApiControl(True, "Drone3")
    client.enableApiControl(True, "Drone4")
    client.enableApiControl(True, "Drone5")
    client.enableApiControl(True, "Drone6")
    client.armDisarm(True, "Lead")
    client.armDisarm(True, "Drone1")
    client.armDisarm(True, "Drone2")
    client.armDisarm(True, "Drone3")
    client.armDisarm(True, "Drone4")
    client.armDisarm(True, "Drone5")
    client.armDisarm(True, "Drone6")


    Swarming.formSwarm(d)


    f1 = client.moveToZAsync(-0.1, 5,vehicle_name="Lead")
    f2 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone1")
    f3 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone2")
    f4 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone3")
    f5 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone4")
    f6 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone5")
    f7 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone6")
    f7.join()
    f6.join()
    f5.join()
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    f1 = client.landAsync(vehicle_name="Lead")
    f2 = client.landAsync(vehicle_name="Drone1")
    f3 = client.landAsync(vehicle_name="Drone2")
    f4 = client.landAsync(vehicle_name="Drone3")
    f5 = client.landAsync(vehicle_name="Drone4")
    f6 = client.landAsync(vehicle_name="Drone5")
    f7 = client.landAsync(vehicle_name="Drone6")
    f7.join()
    f6.join()
    f5.join()
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    client.armDisarm(False, "Lead")
    client.armDisarm(False, "Drone1")
    client.armDisarm(False, "Drone2")
    client.armDisarm(False, "Drone3")
    client.armDisarm(False, "Drone4")
    client.armDisarm(False, "Drone5")
    client.armDisarm(False, "Drone6")
    client.enableApiControl(False, "Lead")
    client.enableApiControl(False, "Drone1")
    client.enableApiControl(False, "Drone2")
    client.enableApiControl(False, "Drone3")
    client.enableApiControl(False, "Drone4")
    client.enableApiControl(False, "Drone5")
    client.enableApiControl(False, "Drone6")
if d == 7:
    client.enableApiControl(True, "Lead")
    client.enableApiControl(True, "Drone1")
    client.enableApiControl(True, "Drone2")
    client.enableApiControl(True, "Drone3")
    client.enableApiControl(True, "Drone4")
    client.enableApiControl(True, "Drone5")
    client.enableApiControl(True, "Drone6")
    client.enableApiControl(True, "Drone7")
    client.armDisarm(True, "Lead")
    client.armDisarm(True, "Drone1")
    client.armDisarm(True, "Drone2")
    client.armDisarm(True, "Drone3")
    client.armDisarm(True, "Drone4")
    client.armDisarm(True, "Drone5")
    client.armDisarm(True, "Drone6")
    client.armDisarm(True, "Drone7")


    Swarming.formSwarm(d)


    f1 = client.moveToZAsync(-0.1, 5,vehicle_name="Lead")
    f2 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone1")
    f3 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone2")
    f4 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone3")
    f5 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone4")
    f6 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone5")
    f7 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone6")
    f8 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone7")
    f8.join()
    f7.join()
    f6.join()
    f5.join()
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    f1 = client.landAsync(vehicle_name="Lead")
    f2 = client.landAsync(vehicle_name="Drone1")
    f3 = client.landAsync(vehicle_name="Drone2")
    f4 = client.landAsync(vehicle_name="Drone3")
    f5 = client.landAsync(vehicle_name="Drone4")
    f6 = client.landAsync(vehicle_name="Drone5")
    f7 = client.landAsync(vehicle_name="Drone6")
    f8 = client.landAsync(vehicle_name="Drone7")
    f8.join()
    f7.join()
    f6.join()
    f5.join()
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    client.armDisarm(False, "Lead")
    client.armDisarm(False, "Drone1")
    client.armDisarm(False, "Drone2")
    client.armDisarm(False, "Drone3")
    client.armDisarm(False, "Drone4")
    client.armDisarm(False, "Drone5")
    client.armDisarm(False, "Drone6")
    client.armDisarm(False, "Drone7")
    client.enableApiControl(False, "Lead")
    client.enableApiControl(False, "Drone1")
    client.enableApiControl(False, "Drone2")
    client.enableApiControl(False, "Drone3")
    client.enableApiControl(False, "Drone4")
    client.enableApiControl(False, "Drone5")
    client.enableApiControl(False, "Drone6")
    client.enableApiControl(False, "Drone7")
if d == 8:
    client.enableApiControl(True, "Lead")
    client.enableApiControl(True, "Drone1")
    client.enableApiControl(True, "Drone2")
    client.enableApiControl(True, "Drone3")
    client.enableApiControl(True, "Drone4")
    client.enableApiControl(True, "Drone5")
    client.enableApiControl(True, "Drone6")
    client.enableApiControl(True, "Drone7")
    client.enableApiControl(True, "Drone8")
    client.armDisarm(True, "Lead")
    client.armDisarm(True, "Drone1")
    client.armDisarm(True, "Drone2")
    client.armDisarm(True, "Drone3")
    client.armDisarm(True, "Drone4")
    client.armDisarm(True, "Drone5")
    client.armDisarm(True, "Drone6")
    client.armDisarm(True, "Drone7")
    client.armDisarm(True, "Drone8")


    Swarming.formSwarm(d)


    f1 = client.moveToZAsync(-0.1, 5,vehicle_name="Lead")
    f2 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone1")
    f3 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone2")
    f4 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone3")
    f5 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone4")
    f6 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone5")
    f7 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone6")
    f8 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone7")
    f9 = client.moveToZAsync(-0.1, 5,vehicle_name="Drone8")
    f9.join()
    f8.join()
    f7.join()
    f6.join()
    f5.join()
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    f1 = client.landAsync(vehicle_name="Lead")
    f2 = client.landAsync(vehicle_name="Drone1")
    f3 = client.landAsync(vehicle_name="Drone2")
    f4 = client.landAsync(vehicle_name="Drone3")
    f5 = client.landAsync(vehicle_name="Drone4")
    f6 = client.landAsync(vehicle_name="Drone5")
    f7 = client.landAsync(vehicle_name="Drone6")
    f8 = client.landAsync(vehicle_name="Drone7")
    f9 = client.landAsync(vehicle_name="Drone8")
    f9.join()
    f8.join()
    f7.join()
    f6.join()
    f5.join()
    f4.join()
    f3.join()
    f2.join()
    f1.join()

    client.armDisarm(False, "Lead")
    client.armDisarm(False, "Drone1")
    client.armDisarm(False, "Drone2")
    client.armDisarm(False, "Drone3")
    client.armDisarm(False, "Drone4")
    client.armDisarm(False, "Drone5")
    client.armDisarm(False, "Drone6")
    client.armDisarm(False, "Drone7")
    client.armDisarm(False, "Drone8")
    client.enableApiControl(False, "Lead")
    client.enableApiControl(False, "Drone1")
    client.enableApiControl(False, "Drone2")
    client.enableApiControl(False, "Drone3")
    client.enableApiControl(False, "Drone4")
    client.enableApiControl(False, "Drone5")
    client.enableApiControl(False, "Drone6")
    client.enableApiControl(False, "Drone7")
    client.enableApiControl(False, "Drone8")